"""empty message

Revision ID: 55082efd7618
Revises: 160be770da62
Create Date: 2025-12-09 01:20:05.539668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55082efd7618'
down_revision = '160be770da62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
